/**
 * NovaCoin ICO Client
 *
 * Client library for interacting with the NovaCoin ICO smart contract.
 * Handles token initialization, ICO management, and token purchases.
 */

const {
    Connection,
    PublicKey,
    Keypair,
    Transaction,
    SystemProgram,
    LAMPORTS_PER_SOL,
    sendAndConfirmTransaction,
} = require('@solana/web3.js');
const {
    createMint,
    getOrCreateAssociatedTokenAccount,
    mintTo,
    TOKEN_PROGRAM_ID,
    getAssociatedTokenAddress,
} = require('@solana/spl-token');
const { Program, AnchorProvider, BN, web3 } = require('@coral-xyz/anchor');
const fs = require('fs');
const path = require('path');

// Load IDL (generated by anchor build)
const IDL_PATH = path.join(__dirname, '../../target/idl/nova_token.json');

class NovaIcoClient {
    /**
     * Create a new ICO client
     * @param {object} config - Configuration
     */
    constructor(config = {}) {
        this.config = {
            network: config.network || 'devnet',
            programId: config.programId,
        };

        const endpoints = {
            'devnet': 'https://api.devnet.solana.com',
            'testnet': 'https://api.testnet.solana.com',
            'mainnet-beta': 'https://api.mainnet-beta.solana.com',
        };

        this.connection = new Connection(endpoints[this.config.network], 'confirmed');
        this.program = null;
        this.provider = null;
    }

    /**
     * Initialize the client with a wallet
     * @param {Keypair} wallet - Wallet keypair
     */
    async initialize(wallet) {
        this.wallet = wallet;

        // Create provider
        this.provider = new AnchorProvider(
            this.connection,
            {
                publicKey: wallet.publicKey,
                signTransaction: async (tx) => {
                    tx.partialSign(wallet);
                    return tx;
                },
                signAllTransactions: async (txs) => {
                    txs.forEach((tx) => tx.partialSign(wallet));
                    return txs;
                },
            },
            { commitment: 'confirmed' }
        );

        // Load IDL and create program
        if (fs.existsSync(IDL_PATH)) {
            const idl = JSON.parse(fs.readFileSync(IDL_PATH, 'utf-8'));
            this.program = new Program(
                idl,
                new PublicKey(this.config.programId),
                this.provider
            );
        } else {
            console.warn('IDL not found. Some features may be unavailable.');
        }

        console.log('ICO Client initialized');
        console.log('Wallet:', wallet.publicKey.toBase58());
        console.log('Network:', this.config.network);
    }

    /**
     * Get PDA addresses
     */
    getPDAs(tokenMint) {
        const [icoConfig] = PublicKey.findProgramAddressSync(
            [Buffer.from('ico_config')],
            new PublicKey(this.config.programId)
        );

        const [icoTokenVault] = PublicKey.findProgramAddressSync(
            [Buffer.from('ico_vault'), tokenMint.toBuffer()],
            new PublicKey(this.config.programId)
        );

        const [purchaseRecord] = PublicKey.findProgramAddressSync(
            [Buffer.from('purchase'), this.wallet.publicKey.toBuffer()],
            new PublicKey(this.config.programId)
        );

        return { icoConfig, icoTokenVault, purchaseRecord };
    }

    /**
     * Create and initialize a new token mint
     * @returns {PublicKey} Token mint address
     */
    async createTokenMint() {
        console.log('Creating NovaCoin token mint...');

        const mint = await createMint(
            this.connection,
            this.wallet,
            this.wallet.publicKey, // Mint authority
            this.wallet.publicKey, // Freeze authority
            9 // 9 decimals
        );

        console.log('Token mint created:', mint.toBase58());

        // Create token account for authority
        const authorityTokenAccount = await getOrCreateAssociatedTokenAccount(
            this.connection,
            this.wallet,
            mint,
            this.wallet.publicKey
        );

        console.log('Authority token account:', authorityTokenAccount.address.toBase58());

        // Mint initial supply (1 billion tokens)
        const totalSupply = 1_000_000_000n * 1_000_000_000n; // 1B with 9 decimals

        await mintTo(
            this.connection,
            this.wallet,
            mint,
            authorityTokenAccount.address,
            this.wallet,
            totalSupply
        );

        console.log('Minted', (totalSupply / 1_000_000_000n).toString(), 'NOVA tokens');

        return mint;
    }

    /**
     * Initialize the ICO
     * @param {PublicKey} tokenMint - Token mint address
     * @param {PublicKey} treasury - Treasury wallet for SOL
     * @param {number} tokensForSale - Number of tokens for sale
     * @param {number} startTime - Unix timestamp for start
     * @param {number} endTime - Unix timestamp for end
     */
    async initializeIco(tokenMint, treasury, tokensForSale, startTime, endTime) {
        if (!this.program) {
            throw new Error('Program not initialized. Make sure IDL exists.');
        }

        const pdas = this.getPDAs(tokenMint);

        const authorityTokenAccount = await getAssociatedTokenAddress(
            tokenMint,
            this.wallet.publicKey
        );

        console.log('Initializing ICO...');

        const tx = await this.program.methods
            .initializeIco(
                new BN(tokensForSale),
                new BN(startTime),
                new BN(endTime)
            )
            .accounts({
                authority: this.wallet.publicKey,
                icoConfig: pdas.icoConfig,
                tokenMint: tokenMint,
                authorityTokenAccount: authorityTokenAccount,
                icoTokenVault: pdas.icoTokenVault,
                treasury: treasury,
                tokenProgram: TOKEN_PROGRAM_ID,
                systemProgram: SystemProgram.programId,
            })
            .signers([this.wallet])
            .rpc();

        console.log('ICO initialized! Tx:', tx);

        return tx;
    }

    /**
     * Set ICO phase
     * @param {number} phase - Phase (0=NotStarted, 1=SeedRound, 2=PrivateSale, 3=PublicSale, 4=Ended)
     */
    async setPhase(phase) {
        if (!this.program) {
            throw new Error('Program not initialized');
        }

        const [icoConfig] = PublicKey.findProgramAddressSync(
            [Buffer.from('ico_config')],
            new PublicKey(this.config.programId)
        );

        const tx = await this.program.methods
            .setPhase(phase)
            .accounts({
                authority: this.wallet.publicKey,
                icoConfig: icoConfig,
            })
            .signers([this.wallet])
            .rpc();

        const phases = ['NotStarted', 'SeedRound', 'PrivateSale', 'PublicSale', 'Ended'];
        console.log(`Phase set to: ${phases[phase]}`);
        console.log('Tx:', tx);

        return tx;
    }

    /**
     * Buy tokens during ICO
     * @param {PublicKey} tokenMint - Token mint address
     * @param {PublicKey} treasury - Treasury wallet
     * @param {number} solAmount - Amount of SOL to spend
     */
    async buyTokens(tokenMint, treasury, solAmount) {
        if (!this.program) {
            throw new Error('Program not initialized');
        }

        const pdas = this.getPDAs(tokenMint);

        const buyerTokenAccount = await getAssociatedTokenAddress(
            tokenMint,
            this.wallet.publicKey
        );

        console.log(`Buying tokens with ${solAmount} SOL...`);

        const lamports = new BN(solAmount * LAMPORTS_PER_SOL);

        const tx = await this.program.methods
            .buyTokens(lamports)
            .accounts({
                buyer: this.wallet.publicKey,
                icoConfig: pdas.icoConfig,
                tokenMint: tokenMint,
                icoTokenVault: pdas.icoTokenVault,
                buyerTokenAccount: buyerTokenAccount,
                purchaseRecord: pdas.purchaseRecord,
                treasury: treasury,
                tokenProgram: TOKEN_PROGRAM_ID,
                associatedTokenProgram: new PublicKey(
                    'ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL'
                ),
                systemProgram: SystemProgram.programId,
            })
            .signers([this.wallet])
            .rpc();

        console.log('Tokens purchased! Tx:', tx);

        return tx;
    }

    /**
     * Get ICO configuration
     */
    async getIcoConfig() {
        if (!this.program) {
            throw new Error('Program not initialized');
        }

        const [icoConfig] = PublicKey.findProgramAddressSync(
            [Buffer.from('ico_config')],
            new PublicKey(this.config.programId)
        );

        const config = await this.program.account.icoConfig.fetch(icoConfig);

        const phases = ['NotStarted', 'SeedRound', 'PrivateSale', 'PublicSale', 'Ended'];

        return {
            authority: config.authority.toBase58(),
            tokenMint: config.tokenMint.toBase58(),
            treasury: config.treasury.toBase58(),
            phase: phases[Object.keys(config.phase)[0]] || 'Unknown',
            totalTokensForSale: config.totalTokensForSale.toString(),
            tokensSold: config.tokensSold.toString(),
            solRaised: (config.solRaised.toNumber() / LAMPORTS_PER_SOL).toFixed(4),
            startTime: new Date(config.startTime.toNumber() * 1000).toISOString(),
            endTime: new Date(config.endTime.toNumber() * 1000).toISOString(),
        };
    }

    /**
     * Get purchase record for a buyer
     * @param {PublicKey} buyer - Buyer public key
     */
    async getPurchaseRecord(buyer) {
        if (!this.program) {
            throw new Error('Program not initialized');
        }

        const [purchaseRecord] = PublicKey.findProgramAddressSync(
            [Buffer.from('purchase'), buyer.toBuffer()],
            new PublicKey(this.config.programId)
        );

        try {
            const record = await this.program.account.purchaseRecord.fetch(purchaseRecord);

            return {
                buyer: record.buyer.toBase58(),
                totalSolSpent: (record.totalSolSpent.toNumber() / LAMPORTS_PER_SOL).toFixed(4),
                totalTokensPurchased: record.totalTokensPurchased.toString(),
            };
        } catch {
            return null;
        }
    }

    /**
     * Request airdrop (devnet only)
     * @param {number} amount - Amount in SOL
     */
    async requestAirdrop(amount = 2) {
        if (this.config.network !== 'devnet') {
            throw new Error('Airdrop only available on devnet');
        }

        const signature = await this.connection.requestAirdrop(
            this.wallet.publicKey,
            amount * LAMPORTS_PER_SOL
        );

        await this.connection.confirmTransaction(signature);
        console.log(`Airdrop of ${amount} SOL received!`);

        return signature;
    }

    /**
     * Get SOL balance
     */
    async getBalance() {
        const balance = await this.connection.getBalance(this.wallet.publicKey);
        return balance / LAMPORTS_PER_SOL;
    }
}

module.exports = { NovaIcoClient };

// CLI usage
if (require.main === module) {
    const args = process.argv.slice(2);
    const command = args[0];

    // Demo usage
    (async () => {
        // Generate a test wallet
        const wallet = Keypair.generate();

        const client = new NovaIcoClient({
            network: 'devnet',
            programId: 'DQXzUhFzKaHJMPLz4Fy57nmkLSJbTvrjbeXwhHxbPNUx', // Replace with deployed program ID
        });

        await client.initialize(wallet);

        switch (command) {
            case 'airdrop':
                await client.requestAirdrop(2);
                const balance = await client.getBalance();
                console.log('Balance:', balance, 'SOL');
                break;

            case 'create-token':
                await client.requestAirdrop(2);
                const mint = await client.createTokenMint();
                console.log('Token mint:', mint.toBase58());
                break;

            case 'status':
                try {
                    const config = await client.getIcoConfig();
                    console.log('ICO Configuration:');
                    console.log(JSON.stringify(config, null, 2));
                } catch (error) {
                    console.log('ICO not initialized yet');
                }
                break;

            default:
                console.log('NovaCoin ICO Client');
                console.log('');
                console.log('Commands:');
                console.log('  airdrop      - Get devnet SOL');
                console.log('  create-token - Create token mint');
                console.log('  status       - Get ICO status');
        }
    })();
}
